[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/login"
  to = "https://buystuffreact.onrender.com/login"
  status = 200
  force = true

[[redirects]]
  from = "/home"
  to = "https://buystuffreact.onrender.com/home"
  status = 200
  force = true

[[redirects]]
  from = "/post/:postId"
  to = "https://buystuffreact.onrender.com/post/:postId"
  status = 200
  force = true

[[redirects]]
  from = "/posts/"
  to = "https://buystuffreact.onrender.com/posts"
  status = 200
  force = true
