[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/api/login"
  to = "https://buystuffreact.onrender.com/login"
  status = 200
  force = true

[[redirects]]
  from = "/api/home"
  to = "https://buystuffreact.onrender.com/home"
  status = 200
  force = true

[[redirects]]
  from = "/api/post/:postId"
  to = "https://buystuffreact.onrender.com/post/:postId"
  status = 200
  force = true
