var flowersData = [
    {
        id: 1,
        size: "large",
        name: "Blue Water Lily (Nil Manel)",
        color: "light",
        occasions: ["religious", "child party", "party", "celebration"],
        fragrance: "yes",
       description:"Indulge in the beauty of this abundant flower bunch, a harmonious blend of captivating shades. Each bloom tells a tale of elegance, whispering celebration. A gift that paints occasions with joy, its vibrant hues creating a lasting memory. Embrace the moment with nature's masterpiece.",
        imageUrl: "https://i.imgur.com/ANEeJk3.jpg",
    },
    {
        id: 2,
        size: "large",
        name: "Red Indian Lily (Rathu Manel)",
        color: "dark",
        occasions: ["religious","party", "child party", "celebration"],
        fragrance: "yes",
       description:"Express your love in an adorable and stunning way with a red lily arrangement. These captivating blooms symbolize passion, desire, and devotion. This enchanting arrangement serves as a beautiful expression of love, captivating the heart with its vibrant color and graceful presence, conveying your deepest affection in an exquisite way.",
        imageUrl: "https://i.imgur.com/GJdl2sG.jpg",
    },
    {
        id: 3,
        size: "large",
        name: "Hairy Water Lily (Olu)",
        color: "light",
        occasions: ["party", "religious", "celebration"],
        fragrance: "yes",
        description: "Behold a captivating cascade of nature's opulence, a bouquet that transcends beauty. Each blossom is a jewel, a symphony of vibrant hues and delicate fragrances. A living masterpiece that enchants the senses, embodying the essence of celebration and adding an exquisite touch to any occasion.",
        imageUrl: "https://i.imgur.com/1rLOSUa.jpg",
    },
    {
        id: 4,
        size: "large",
        name: "Barberton Daisy (Barbandaisiya)",
        color: "dark",
        occasions: ["party", "religious", "child party", "celebration"],
        fragrance: "no",
        description: "Breathe life into any moment with our enchanting flower bunch. Overflowing with colorful blooms, it's a gift that speaks volumes of love and appreciation. Whether for a special occasion or just because, let these fresh flowers bring joy and warmth to your loved one's heart.",
        imageUrl: "https://i.imgur.com/hekaDrw.jpg",
    },
    {
        id: 5,
        size: "small",
        name: "Pinwheel Flower (Watu Sudda)",
        color: "light",
        occasions: ["party", "child party", "religious", "celebration"],
        fragrance: "no",
        description: "This delightful flower bunch features an array of pretty flowers, a simple yet captivating display of nature's grace. Each bloom exudes its own unique charm, coming together in perfect harmony. It's a heartfelt gift that whispers beauty and adds a touch of loveliness to any moment or occasion.",
        imageUrl: "https://i.imgur.com/VS5B69V.jpg",
    },
    {
        id: 6,
        size: "medium",
        name: "Ash Gourd (Puhul)",
        color: "light",
        occasions: ["party", "child party", "religious", "celebration"],
        fragrance: "no",
        description: "Make someone's birthday extra special with this lovely and stunning bunch of chrysanthemums. Bursting with vibrant colors and charming blooms, this bouquet radiates joy and happiness. It's a wonderful greeting that conveys warm birthday wishes and adds a touch of beauty to their celebration, making it truly memorable.",
        imageUrl: "https://i.imgur.com/ndLDMih.jpg",
    },
    {
        id: 7,
        size: "medium",
        name: "Anthurium",
        color: "dark",
        occasions: ["party", "child party", "celebration"],
        fragrance: "no",
        description: "Anthuriums are gorgeous, easy-to-care-for flowering plants, and they bloom all year round. The flowers are long-lasting, So, you will always be able to admire a couple of its flowers among its glossy green foliage. Due to their long-lasting nature and open, heart shape, anthuriums are popular as hospitality gifts.",
      imageUrl: "https://i.imgur.com/Xx2lS0U.jpg",
    },
    {
        id: 8,
        size: "medium",
        name: "Queen of the Night (Kadupul)",
        color: "light",
        occasions: ["party", "religious", "child party", "celebration"],
        fragrance: "yes",
        description: "Embrace the elegance of celebration with this delightful bunch adorned with lovely lilies. Each petal holds a touch of grace, a promise of joy. A bouquet that captures hearts and radiates happiness, perfect for every occasion. Let these lilies paint your moments with beauty and bliss.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Epiphyllum_oxypetalum_flower.JPG/1200px-Epiphyllum_oxypetalum_flower.JPG",
    },
    {
        id: 9,
        size: "medium",
        name: "Rose (Rosa)",
        color: "dark",
        occasions: ["party", "child party", "celebration"],
        fragrance: "yes",
        description: "Bring a smile to your loved one's face with this lovely floral bunch with fragrant red roses designed to brighten up their day. Whether it's to celebrate a special occasion or simply to show your appreciation, this beautiful display of fresh blooms is the perfect way to convey your heartfelt emotions and make them feel special.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Rosa_Precious_platinum.jpg/220px-Rosa_Precious_platinum.jpg",
    },
    {
        id: 10,
        size: "small",
        name: "Butterfly-Pea (Nil Katarolu)",
        color: "dark",
        occasions: ["party", "child party", "religious", "celebration"],
        fragrance: "yes",
        description: "Wrapped in a rustic embrace of purple paper, this magnificent bouquet is a symphony of nature's splendor. The flowers are carefully selected to represent the unique qualities that make her so special. With each petal oozing an aura of mystique and allure, this floral masterpiece is a testament to the untamed beauty of the natural world. Own this exquisite creation today and let its captivating aura take your breath away. ",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/76/Clitoria_%28253000626%29.jpg",
    },
    {
        id: 11,
        size: "large",
        name: "Lotus (Nelum)",
        color: "light",
        occasions: ["religious", "celebration"],
        fragrance: "yes",
        description: "Indulge in the beauty of a gorgeous and lovely bunch featuring asiatic pink lilies and purple macclum daisies. The delicate pink lilies symbolize love and admiration, while the vibrant purple macclum daisies add a touch of enchantment. This stunning combination creates a captivating bouquet that celebrates beauty and elegance.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Nelumbo-nucifera-3-_1200.jpg/270px-Nelumbo-nucifera-3-_1200.jpg",
    },
    {
        id: 12,
        size: "medium",
        name: "Orchid (Wanaraja)",
        color: "dark",
        occasions: ["party", "celebration", "religious"],
        fragrance: "yes",
        description: "Make your special occasion even more memorable with the ethereal beauty of our orchid garland with two layers of purple orchids. Delicately strung together, these stunning blooms add a touch of exotic elegance and create a whimsical atmosphere that will enchant all your guests.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Orchid_Phalaenopsis_hybrid.jpg/800px-Orchid_Phalaenopsis_hybrid.jpg",
    },
    {
        id: 13,
        size: "small",
        name: "Jasmine (Pichcha)",
        color: "light",
        occasions: ["religious", "celebration"],
        fragrance: "yes",
        description: "This extra-special floral surprise is the perfect way to confess your love in style and show that special someone how much they mean to you. With this beautiful gesture, you can let them know that they made you believe in love and that they hold a special place in your heart.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Jasminum_grandiflorum_%28Oleaceae%29.jpg/1200px-Jasminum_grandiflorum_%28Oleaceae%29.jpg",
    },
    {
        id: 14,
        size: "small",
        name: "Ixora (Rathmal)",
        color: "dark",
        occasions: ["party", "religious", "child party", "celebration"],
        fragrance: "no",
         description: "Elevate your corporate gifting with a fresh flower garland. Meticulously designed, it symbolizes growth, unity, and appreciation. A tasteful gesture, this garland adds a touch of nature's beauty to your business relationships, expressing respect and gratitude in a truly memorable way.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/IxoraCoccineaMiami.JPG/269px-IxoraCoccineaMiami.JPG",
    },
    {
        id: 15,
        size: "medium",
        name: "Hibiscus (Wada Mal)",
        color: "light",
        occasions: ["religious", "party", "child party", "celebration"],
        fragrance: "no",
        description: "Nothing is sweeter than a bunch of vibrant chrysanthemums! Flowers are the right way to captivate and pamper your dearest ones! Gift this Beautiful Chrysanthemum 10 stems bunch including sandriana wrapped in a pastel shade of light pink to indulge their dreams, which is appropriate for this colorful season",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Hibiscus_Albo_Laciniatus_%281%29.jpg",
    },
    {
        id: 16,
        size: "medium",
        name: "Tulip",
        color: "light",
        occasions: ["celebration", "religious", "party", "child party"],
        fragrance: "yes",
        description: "Tulips hold cultural importance in various societies, often symbolizing love, elegance, and grace. They are frequently used in floral arrangements for events, celebrations, and religious ceremonies.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Yonina_Tulip.jpg/220px-Yonina_Tulip.jpg",
    },
    {
        id: 17,
        size: "small",
        name: "Carnation",
        color: "dark",
        occasions: ["party", "celebration"],
        fragrance: "no",
        description: "Carnations are often chosen for special occasions such as weddings, Mother's Day, and other celebrations. Their availability in a variety of colors allows for customization based on the theme or sentiment of the event.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3b/W_carnation4051.jpg",
    },
    {
        id: 18,
        size: "small",
        name: "Daisy",
        color: "light",
        occasions: ["party", "religious", "child party", "celebration"],
        fragrance: "no",
        description: "Delight in the simplicity and charm of the Daisy, a flower that embodies pure elegance. With its pristine white petals surrounding a golden center, the Daisy is a symbol of innocence and joy. As you bring home this bloom, envision a touch of natural radiance adorning your space, brightening every corner with its timeless beauty. Versatile and enduring, the Daisy effortlessly adds a touch of grace to any bouquet or arrangement, making it a delightful choice for those seeking the perfect blend of simplicity and sophistication.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/53/Belis_peremnis_-_panoramio.jpg",
    },
    {
        id: 19,
        size: "medium",
        name: "Daffodil",
        color: "light",
        occasions: ["celebration", "religious"],
        fragrance: "yes",
        description: "Elevate your floral experience with the captivating charm of Daffodils, a golden treasure that transforms any bouquet into a celebration of nature's optimism. Bring home the sunshine with Daffodils and let their brilliance illuminate your world.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Narcissus_pseudonarcissus_flower_300303.jpg",
    },
    {
        id: 20,
        size: "small",
        name: "Lavender",
        color: "light",
        occasions: ["party", "celebration"],
        fragrance: "yes",
        description: "Embark on a sensory journey with the captivating Lavender, a flower that transcends beauty to envelop you in its soothing embrace. Immerse yourself in the elegant purple hues and breathe in the enchanting fragrance, a symphony of tranquility and calm.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/English_Lavender.JPG/220px-English_Lavender.JPG",
    },
    {
        id: 21,
        size: "large",
        name: "Chrysanthemum",
        color: "light",
        occasions: ["party", "celebration"],
        fragrance: "no",
        description: "This regal flower, with its myriad of colors and lush layers, is more than a bloom—it's a statement of sophistication. As you invite the Chrysanthemum into your space, envision a burst of floral grandeur, a testament to nature's artistry. Versatile and captivating, Chrysanthemums effortlessly elevate any arrangement, making them a must-have for the discerning flower enthusiast. Immerse yourself in the allure of Chrysanthemums, where every blossom whispers tales of grace and refinement. Transform your surroundings with the exquisite charm of these botanical jewels.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Chrysanthemum_morifolium_08NOV.jpg",
    },
    {
        id: 22,
        size: "small",
        name: "Poppy",
        color: "light",
        occasions: ["celebration", "party"],
        fragrance: "yes",
        description: "Unveil the allure of the Poppy, a flower that dances with vibrant hues and whispers tales of enchantment. Grace your space with its delicate yet bold presence, as the Poppy effortlessly commands attention with its captivating beauty. As a symbol of imagination and creativity, the Poppy transcends the ordinary, offering a touch of artistic flair to any arrangement. Picture the elegance of Poppies adorning your home, a burst of color that speaks volumes of your unique taste. ",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Blood_Lily_--_Scadoxus_multiflorus.jpg/220px-Blood_Lily_--_Scadoxus_multiflorus.jpg",
    },
    {
        id: 23,
        size: "small",
        name: "Marigold",
        color: "light",
        occasions: ["party", "celebration"],
        fragrance: "no",
        description: "Immerse yourself in the radiant world of Marigolds, where vibrant hues and uplifting energy collide. Bursting with shades of gold and orange, the Marigold is more than a flower—it's a celebration of joy and positivity. Envision these cheerful blooms transforming your space into a lively haven, radiating warmth and charm. With a rich cultural significance and a symbol of prosperity, Marigolds stand as a testament to life's abundance. Elevate your floral arrangements with the irresistible allure of Marigolds, a botanical ode to happiness and abundance. ",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/Yellow_French_Marigold_Flower.jpg",
    },
    {
        id: 24,
        size: "small",
        name: "Snapdragon",
        color: "dark",
        occasions: ["celebration", "child party"],
        fragrance: "yes",
        description: "Step into a world of whimsy with the Snapdragon, a flower that adds a touch of playfulness to your bouquet. Imagine the Snapdragon's enchanting stalks, resembling dragon jaws ready to snap shut. These delightful blooms bring an element of surprise and joy to any floral arrangement, making them a must-have for those who appreciate nature's delightful quirks. As the Snapdragon graces your space, it not only captivates the eyes but sparks conversations and smiles. ",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Antirrhinum_majus_San_Antonio.jpg/1200px-Antirrhinum_majus_San_Antonio.jpg",
    },
    {
        id: 25,
        size: "small",
        name: "Hydrangea",
        color: "light",
        occasions: ["party", "religious", "celebration"],
        fragrance: "no",
        description: "Step into a garden of elegance with the Hydrangea, a blossom that whispers tales of timeless beauty. Imagine clusters of delicate petals forming lush, voluminous blooms in hues that paint a dreamscape of serenity. Hydrangeas are not merely flowers; they are graceful statements of refinement and sophistication. Picture these botanical treasures gracing your arrangements, transforming any space into a sanctuary of tranquility and charm. Embrace the Hydrangea, a symbol of grace that adds a touch of classic beauty to every bouquet.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Hydrangea_macrophylla_-_Bigleaf_hydrangea2.jpg/1200px-Hydrangea_macrophylla_-_Bigleaf_hydrangea2.jpg",
    },
    {
        id: 26,
        size: "small",
        name: "Lily of the Valley",
        color: "light",
        occasions: ["celebration"],
        fragrance: "yes",
        description: "Lily of the Valley is a whisper of purity and sweetness, adorning any bouquet with its timeless allure. Envision these dainty blooms gracing your space, infusing it with an air of sophistication and natural grace. Elevate your floral arrangements with the captivating presence of Lily of the Valley, where every petal tells a story of delicate beauty and refined taste. Embrace the enchantment of Lily of the Valley, a floral jewel that adds a touch of timeless allure to your collection.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Lily_of_the_valley_777.jpg/1280px-Lily_of_the_valley_777.jpg",
    },
    {
        id: 27,
        size: "medium",
        name: "Cherry Blossom (Sri Lankan Sakura)",
        color: "light",
        occasions: ["celebration", "religious"],
        fragrance: "yes",
        description: " the Sri Lankan Sakura is a unique celebration of nature's grace, offering a touch of exotic allure to your collection. Envision these enchanting blooms gracing your space, infusing it with the rare and captivating beauty of Sri Lankan Sakura. Elevate your floral experience with this botanical treasure, a symbol of fleeting beauty and the elegance of island flora. Embrace the allure of Sri Lankan Sakura, a floral gem that captures the essence of a tropical haven.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/2014-05-10_12_34_11_Flowering_Cherry_along_New_Jersey_Route_29_in_Hopewell_Township%2C_New_Jersey.JPG/220px-2014-05-10_12_34_11_Flowering_Cherry_along_New_Jersey_Route_29_in_Hopewell_Township%2C_New_Jersey.JPG",
    },
    {
        id: 28,
        size: "large",
        name: "Sunflower",
        color: "light",
        occasions: ["celebration", "child party"],
        fragrance: "no",
        description: "Picture these vibrant blooms, their faces following the sun, a living testament to the beauty of optimism. Sunflowers are not just flowers; they are nature's sunbeams, transforming any space into a haven of positivity. Envision these cheerful blooms gracing your surroundings, their golden hues brightening your day with a touch of natural exuberance. Elevate your floral experience with the irresistible charm of Sunflowers, where every petal tells a story of sunshine and boundless beauty.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Sunflower_Kamand_DSC_2856.jpg/394px-Sunflower_Kamand_DSC_2856.jpg",
    },
    {
        id: 29,
        size: "medium",
        name: "Dahlia",
        color: "light",
        occasions: ["party", "celebration"],
        fragrance: "no",
        description: "Indulge in the opulent allure of the Dahlia, a flower that unfolds into a botanical masterpiece. Envision intricate petals forming a vibrant display of color and texture, turning every arrangement into a work of art. More than a flower, the Dahlia is a symbol of elegance and variety, offering a diverse palette to elevate your floral experience. Picture these captivating blooms gracing your space, each one a unique expression of nature's creativity. Elevate your floral arrangements with the enchanting charm of Dahlias, where sophistication meets a burst of botanical splendor.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Dahlia_x_hybrida.jpg",
    },
    {
        id: 30,
        size: "medium",
        name: "Plumeria (Araliya)",
        color: "light",
        occasions: ["party", "religious", "celebration"],
        fragrance: "yes",
        description: "Envision the delicate petals forming an intricate dance of purity and grace, reminiscent of a botanical masterpiece. More than a flower, the Araliya is a symbol of refined beauty, transforming any space into a haven of sophistication. Picture these enchanting blooms gracing your surroundings, infusing it with the serene charm of nature's grace. Elevate your floral arrangements with the irresistible allure of Araliyas, where each bloom is a testament to the delicate artistry of flora.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Plumeria-0006-Zachi-Evenor.jpg/200px-Plumeria-0006-Zachi-Evenor.jpg",
    },
];

export default flowersData